In [459]:
import pandas as pd

In [460]:
cities_emissions_2016 = pd.read_csv('data/2016_-_Cities_Emissions_Reduction_Targets_20240207.csv',sep=',')
cities_emissions_2016.head()
cities_emissions_2016[cities_emissions_2016['Country'] == "Denmark"]

,Organisation,Account No,Country,City Short Name,C40,Reporting Year,Sector,Target boundary,Baseline year,Baseline emissions (metric tonnes CO2e),Percentage reduction target,Target date,Comment,City Location,Country Location
0,Odder Kommune,58796,Denmark,Odder Kommune,NaN,2016,Total,NaN,2010,6136.0,2.0,NaN,NaN,"(55.975718, 10.149958)","(56.26392, 9.501785)"
2,Egedal Municipality,62855,Denmark,Egedal Municipality,NaN,2016,Total,NaN,2009,268000.0,7.0,2020.0,The municipality are increasing in terms of ci...,"(55.795045, 12.238733)","(56.26392, 9.501785)"
7,Aarhus Kommune,54408,Denmark,Aarhus Kommune,NaN,2016,Total,community,2008,2100000.0,100.0,2030.0,NaN,"(56.168393, 10.137373)","(56.26392, 9.501785)"
13,City of Ærøskøbing,58609,Denmark,City of Ærøskøbing,NaN,2016,Total,NaN,2015,NaN,10.0,NaN,NaN,"(54.891456, 10.404684)","(56.26392, 9.501785)"
44,Gladsaxe Kommune,59165,Denmark,Gladsaxe Kommune,NaN,2016,Total,Total municipal inventory,2007,499740.0,20.0,2020.0,NaN,"(55.733461, 12.488686)","(56.26392, 9.501785)"
47,Hoeje-Taastrup Kommune,58489,Denmark,Hoeje-Taastrup Kommune,NaN,2016,Total,NaN,2012,310000.0,98.0,2050.0,until 2020 3 % reduction per year\n2035 Fossil...,"(55.656328, 12.2898)","(56.26392, 9.501785)"
48,Hørsholm Kommune,58797,Denmark,Hørsholm Kommune,NaN,2016,Total,NaN,2010,182657.0,20.0,2020.0,NaN,"(55.883514, 12.504924)","(56.26392, 9.501785)"
52,Sonderborg Kommune,58488,Denmark,Sonderborg Kommune,NaN,2016,Total,NaN,2007,180500.0,25.0,2015.0,NaN,"(54.913811, 9.792178)","(56.26392, 9.501785)"
53,Sonderborg Kommune,58488,Denmark,Sonderborg Kommune,NaN,2016,Total,NaN,2007,361000.0,50.0,2020.0,NaN,"(54.913811, 9.792178)","(56.26392, 9.501785)"
54,Sonderborg Kommune,58488,Denmark,Sonderborg Kommune,NaN,2016,NaN,NaN,2007,722000.0,100.0,2029.0,NaN,"(54.913811, 9.792178)","(56.26392, 9.501785)"
79,City of Copenhagen,31009,Denmark,Copenhagen,C40,2016,Total,All sources,2005,2541000.0,20.0,2015.0,NaN,"(55.6760968, 12.5683371)","(56.26392, 9.501785)"
80,City of Copenhagen,31009,Denmark,Copenhagen,C40,2016,Total,All sources,2010,2240000.0,100.0,2025.0,NaN,"(55.6760968, 12.5683371)","(56.26392, 9.501785)"
266,Frederikshavn Kommune,60577,Denmark,Frederikshavn Kommune,NaN,2016,Total,NaN,2010,547000.0,97.0,2030.0,NaN,"(57.442711, 10.521006)","(56.26392, 9.501785)"

In [461]:
citywide_emissions_2016 = pd.read_csv('data/2016_-_Citywide_GHG_Emissions_20240207.csv',sep=',')
citywide_emissions_2016.head()

citywide_emissions_2016[citywide_emissions_2016['Country'] == "Denmark"]

citywide_emissions_2016.columns

Index(['Account Number', 'City Name', 'Country', 'City Short Name', 'C40',
       'Reporting Year', 'Measurement Year', 'Boundary', 'Primary Methodology',
       'Methodology Details', 'Gases included',
       'Total City-wide Emissions (metric tonnes CO2e)',
       'Total Scope 1 Emissions (metric tonnes CO2e)',
       'Total Scope 2 Emissions (metric tonnes CO2e)',
       'Increase/Decrease from last year',
       'Reason for increase/decrease in emissions', 'Current Population Year',
       'Current Population', 'City GDP', 'GDP Currency', 'Year of GDP',
       'GDP Source', 'Average annual temperature (in Celsius)',
       ' Land area (in square km)', 'Average altitude (m)', 'City Location',
       'Country Location'],
      dtype='object')

In [462]:
community_emissions_2017 = pd.read_csv('data/2017_-_Cities_Community_Wide_Emissions.csv',sep=',')
community_emissions_2017.head()

community_emissions_2017[community_emissions_2017['Country'] == "Denmark"]

,Account number,Organization,City,Country,Region,C40,Access,Reporting year,Accounting year,Boundary,...,Population year,GDP,GDP Currency,GDP Year,GDP Source,Average annual temperature (in Celsius),Average altitude (m),Land area (in square km),City Location,Country Location
27,59180,Middelfart Kommune,Middelfart,Denmark,Europe,NaN,Public,2017,2015-01-01 - 2015-12-31,Administrative boundary of a local government,...,2017,2.190900e+09,DKK Danish Krone,2016.0,NaN,8.0,21.0,299.5,"(55.470958, 9.872643)","(56.26392, 9.501785)"
36,58489,Hoeje-Taastrup Kommune,Hoeje-Taastrup,Denmark,Europe,NaN,Public,2017,2016-01-01 - 2016-12-31,Administrative boundary of a local government,...,2016,2.563637e+10,DKK Danish Krone,2012.0,Danmarks Statistik,8.1,27.0,78.0,"(55.656328, 12.2898)","(56.26392, 9.501785)"
69,31009,City of Copenhagen,Copenhagen,Denmark,Europe,C40,Public,2017,2015-01-01 - 2015-12-31,Administrative boundary of a local government,...,2016,3.231830e+11,DKK Danish Krone,2015.0,"Danmarks Statistik, Statistics Denmark",8.0,9.0,86.0,"(55.6760968, 12.5683371)","(56.26392, 9.501785)"
104,59165,Gladsaxe Kommune,Gladsaxe,Denmark,Europe,NaN,Public,2017,2015-01-01 - 2015-12-31,A metropolitan area,...,2015,3.590000e+10,DKK Danish Krone,2015.0,Statistic Denmark,9.4,31.0,24.9,"(55.733461, 12.488686)","(56.26392, 9.501785)"
136,54408,Aarhus Kommune,Aarhus,Denmark,Europe,NaN,Public,2017,2008-01-01 - 2016-01-01,Administrative boundary of a local government,...,2017,NaN,NaN,NaN,NaN,NaN,NaN,468.0,"(56.168393, 10.137373)","(56.26392, 9.501785)"
158,58488,Sonderborg Kommune,Sonderborg,Denmark,Europe,NaN,Public,2017,2015-01-01 - 2015-12-31,Administrative boundary of a local government,...,2017,2.357007e+09,USD US Dollar,2013.0,NaN,9.6,NaN,496.6,"(54.913811, 9.792178)","(56.26392, 9.501785)"
164,58610,Municipality of Hjørring,Hjørring,Denmark,Europe,NaN,Public,2017,2014-01-01 - 2014-12-31,Other: Energy plan for Hjoerring Municipality,...,2016,1.908803e+10,DKK Danish Krone,NaN,http://www.danskbyggeri.dk/media/7648/regional...,7.5,22.0,7.5,"(57.4568, 9.9958)","(56.26392, 9.501785)"
166,62855,Egedal Municipality,Egedal,Denmark,Europe,NaN,Public,2017,2014-01-01 - 2014-12-31,Administrative boundary of a local government,...,2015,1.700000e+10,DKK Danish Krone,2015.0,NaN,8.0,29.0,126.0,"(55.795045, 12.238733)","(56.26392, 9.501785)"
177,58671,Elsinore Municipality,Elsinore,Denmark,Europe,NaN,Public,2017,2015-01-01 - 2015-12-31,Administrative boundary of a local government,...,2015,1.985000e+09,DKK Danish Krone,2015.0,The Ministry of Finance,8.5,8.0,119.0,"(56.0308, 12.5921)","(56.2639, 9.5018)"
193,58609,City of Ærøskøbing,Ærøskøbing,Denmark,Europe,NaN,Public,2017,2016-01-01 - 2016-12-31,Administrative boundary of a local government,...,2017,NaN,NaN,NaN,NaN,10.0,10.0,88.0,"(54.891456, 10.404684)","(56.26392, 9.501785)"
200,60433,City of Hvidovre,Hvidovre,Denmark,Europe,NaN,Public,2017,2014-01-01 - 2014-12-31,Administrative boundary of a local government,...,2016,1.870903e+10,DKK Danish Krone,2015.0,Based on population and national GDP 2014,7.7,10.0,25.0,"(55.642522, 12.475386)","(56.26392, 9.501785)"

In [463]:
cities_emissions_2017 = pd.read_csv('data/2017_-_Cities_Emissions_Reduction_Targets_20240207.csv',sep=',')
cities_emissions_2017.head()

cities_emissions_2017[cities_emissions_2017['Country'] == "Denmark"]

,Account No,Organisation,City,Country,Region,Access,C40,Reporting year,Type of target,Sector,...,Baseline emissions (metric tonnes CO2e),Percentage reduction target,Target date,Estimated business as usual absolute emissions in target year (metric tonnes CO2e),​Intensity unit (emissions per),Comment,Population,Population Year,City Location,Country Location
0,54408,Aarhus Kommune,Aarhus,Denmark,Europe,Public,NaN,2017,Absolute target,NaN,...,NaN,100.0,2030,NaN,NaN,NaN,336000.0,2017.0,"(56.168393, 10.137373)","(56.26392, 9.501785)"
38,58609,City of Ærøskøbing,Ærøskøbing,Denmark,Europe,Public,NaN,2017,Absolute target,NaN,...,NaN,10.0,NaN,NaN,NaN,NaN,6180.0,2017.0,"(54.891456, 10.404684)","(56.26392, 9.501785)"
95,31009,City of Copenhagen,Copenhagen,Denmark,Europe,Public,C40,2017,Baseline scenario (business as usual) target,Total,...,NaN,NaN,2025,900000.0,NaN,NaN,602504.0,2016.0,"(55.6760968, 12.5683371)","(56.26392, 9.501785)"
274,62855,Egedal Municipality,Egedal,Denmark,Europe,Public,NaN,2017,Absolute target,Total,...,268000.0,7.0,2020,NaN,NaN,The municipality are increasing in terms of ci...,42000.0,2015.0,"(55.795045, 12.238733)","(56.26392, 9.501785)"
275,58671,Elsinore Municipality,Elsinore,Denmark,Europe,Public,NaN,2017,Absolute target,Total,...,415000.0,20.0,2020,NaN,NaN,As a signatory of Covenant of Mayors (now comb...,61632.0,2015.0,"(56.0308, 12.5921)","(56.2639, 9.5018)"
276,58671,Elsinore Municipality,Elsinore,Denmark,Europe,Public,NaN,2017,Absolute target,Total,...,415000.0,85.0,2030,NaN,NaN,Maximum 1 ton CO2eq per citizen by 2030. That ...,61632.0,2015.0,"(56.0308, 12.5921)","(56.2639, 9.5018)"
277,58671,Elsinore Municipality,Elsinore,Denmark,Europe,Public,NaN,2017,Absolute target,Total,...,415000.0,100.0,2050,NaN,NaN,Carbon neutral by 2050 at the latest.,61632.0,2015.0,"(56.0308, 12.5921)","(56.2639, 9.5018)"
279,63543,Fredensborg Kommune,Fredensborg,Denmark,Europe,Public,NaN,2017,Absolute target,Total,...,NaN,25.0,2020,NaN,NaN,In 2016 and 2017 a methodology change to the G...,40112.0,2016.0,"(55.9747, 12.4058)","(56.26392, 9.501785)"
280,63543,Fredensborg Kommune,Fredensborg,Denmark,Europe,Public,NaN,2017,Absolute target,Total,...,NaN,100.0,2050,NaN,NaN,In 2016 and 2017 a methodology change to the G...,40112.0,2016.0,"(55.9747, 12.4058)","(56.26392, 9.501785)"
281,60577,Frederikshavn Kommune,Frederikshavn,Denmark,Europe,Public,NaN,2017,Absolute target,Total,...,547000.0,100.0,2030,NaN,NaN,Fossil energy consumption related to private c...,60379.0,2015.0,"(57.442711, 10.521006)","(56.26392, 9.501785)"
287,59165,Gladsaxe Kommune,Gladsaxe,Denmark,Europe,Public,NaN,2017,Absolute target,Total,...,499740.0,40.0,2020,NaN,NaN,NaN,67347.0,2015.0,"(55.733461, 12.488686)","(56.26392, 9.501785)"
297,58489,Hoeje-Taastrup Kommune,Hoeje-Taastrup,Denmark,Europe,Public,NaN,2017,Absolute target,Total,...,312026.0,95.0,2050,NaN,NaN,NaN,49960.0,2016.0,"(55.656328, 12.2898)","(56.26392, 9.501785)"
298,58797,Hørsholm Kommune,Hørsholm,Denmark,Europe,Public,NaN,2017,Absolute target,NaN,...,NaN,20.0,2020,NaN,NaN,NaN,24709.0,2014.0,"(55.883514, 12.504924)","(56.26392, 9.501785)"
308,63542,Lejre Kommune,Lejre,Denmark,Europe,Public,NaN,2017,Absolute target,NaN,...,NaN,30.0,2020,NaN,NaN,NaN,27317.0,2016.0,"(55.6013, 11.9645)","(56.26392, 9.501785)"
312,59180,Middelfart Kommune,Middelfart,Denmark,Europe,Public,NaN,2017,Absolute target,Buildings,...,70365.0,NaN,2025,NaN,NaN,NaN,38093.0,2017.0,"(55.470958, 9.872643)","(56.26392, 9.501785)"
313,59180,Middelfart Kommune,Middelfart,Denmark,Europe,Public,NaN,2017,Absolute target,Transport,...,104276.0,NaN,2025,NaN,NaN,NaN,38093.0,2017.0,"(55.470958, 9.872643)","(56.26392, 9.501785)"
314,59180,Middelfart Kommune,Middelfart,Denmark,Europe,Public,NaN,2017,Absolute target,Total,...,362234.0,50.0,2025,NaN,NaN,NaN,38093.0,2017.0,"(55.470958, 9.872643)","(56.26392, 9.501785)"
363,58781,Ringkøbing-Skjern Kommune,Ringkøbing-Skjern,Denmark,Europe,Public,NaN,2017,Absolute target,Total,...,491364.0,100.0,2020,NaN,NaN,"http://www.energi2020.dk/english, See informat...",58176.0,2012.0,"(56.0447, 8.5059)","(56.26392, 9.501785)"
367,58488,Sonderborg Kommune,Sonderborg,Denmark,Europe,Public,NaN,2017,Absolute target,NaN,...,4763894.0,25.0,2015,NaN,NaN,NaN,74801.0,2017.0,"(54.913811, 9.792178)","(56.26392, 9.501785)"
368,58488,Sonderborg Kommune,Sonderborg,Denmark,Europe,Public,NaN,2017,Absolute target,NaN,...,4763894.0,50.0,2020,NaN,NaN,NaN,74801.0,2017.0,"(54.913811, 9.792178)","(56.26392, 9.501785)"
369,58488,Sonderborg Kommune,Sonderborg,Denmark,Europe,Public,NaN,2017,Absolute target,NaN,...,4763894.0,100.0,2029,NaN,NaN,NaN,74801.0,2017.0,"(54.913811, 9.792178)","(56.26392, 9.501785)"

In [464]:
cities_risk_2023 = pd.read_csv('data/2023_Cities_Climate_Risk_and_Vulnerability_Assessments_20240207.csv',sep=',')
cities_risk_2023.head()

cities_risk_2023[cities_risk_2023['Country/Area'] == "Denmark"]

,Questionnaire,Organization Number,Organization Name,City,Country/Area,CDP Region,C40 City,GCoM City,Access,Assessment attachment and/or direct link,Confirm attachment/link provided,Boundary of assessment relative to jurisdiction boundary,Year of publication or approval,Factors considered in assessment,Primary author(s) of assessment,Does the city have adaptation goal(s) and/or an adaptation plan?,Population,Population Year,City Location,Last update
97,Cities 2023,58489,Høje-Taastrup Municipality,Hoeje-Taastrup,Denmark,Europe,False,True,public,Kommende lukning af Taastrup Valby Kildeplads.pdf,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2018.0,Assessment considers vulnerable populations,"Consultant; Other, please specify: municipal e...",Adaptation goal(s),53053,2022.0,POINT (12.2898 55.6563),02/07/2024 04:14:16 AM
136,Cities 2023,58489,Høje-Taastrup Municipality,Hoeje-Taastrup,Denmark,Europe,False,True,public,Grundvand.pdf,The assessment can be accessed (unrestricted) ...,Larger - covers the whole jurisdiction and adj...,2018.0,Assessment considers water security,"Other, please specify: Published by Egedal Mun...",Adaptation goal(s),53053,2022.0,POINT (12.2898 55.6563),02/07/2024 04:14:16 AM
184,Cities 2023,59180,Middelfart Municipality,Middelfart,Denmark,Europe,False,True,public,https://middelfart.viewer.dkplan.niras.dk/plan...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2022.0,A process has been established for prioritizin...,Dedicated team within jurisdiction,Adaptation goal(s) and adaptation plan,40000,2023.0,POINT (9.87264 55.471),02/07/2024 04:14:16 AM
213,Cities 2023,54408,Aarhus Municipality,Aarhus,Denmark,Europe,False,True,public,https://www.aarhus.dk/media/55658/klimatilpasn...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2020.0,A process has been established for prioritizin...,Relevant department within jurisdiction,Adaptation goal(s) and adaptation plan,362235,2023.0,POINT (10.1374 56.1684),02/07/2024 04:14:16 AM
238,Cities 2023,31009,Copenhagen Municipality,Copenhagen,Denmark,Europe,True,True,public,https://kk.sites.itera.dk/apps/kk_pub2/pdf/191...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2017.0,A process has been established for prioritizin...,Consultant; Dedicated team within jurisdiction,Adaptation goal(s) and adaptation plan,644425,2022.0,POINT (12.5683 55.6761),02/07/2024 04:14:16 AM
309,Cities 2023,31009,Copenhagen Municipality,Copenhagen,Denmark,Europe,True,True,public,https://international.kk.dk/sites/default/file...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2011.0,A process has been established for prioritizin...,Consultant; Dedicated team within jurisdiction...,Adaptation goal(s) and adaptation plan,644425,2022.0,POINT (12.5683 55.6761),02/07/2024 04:14:16 AM
438,Cities 2023,73892,Holbæk Municipality,NaN,Denmark,Europe,False,True,public,https://holbaek.dk/media/yeih5mpy/klimatilpasn...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2022.0,A process has been established for prioritizin...,Consultant,Adaptation plan,72810,2022.0,NaN,02/07/2024 04:14:16 AM
472,Cities 2023,918147,Fanø Municipality,NaN,Denmark,Europe,False,False,public,FanoeKommune-Risikostryingsplan-2021_vedtaget.pdf,The assessment has been attached,Smaller - covers only part of the jurisdiction...,2021.0,A process has been established for prioritizin...,Consultant; Relevant department within jurisdi...,Adaptation goal(s) and adaptation plan,3427,2022.0,POINT (8.4145 55.413),02/07/2024 04:14:16 AM
675,Cities 2023,60577,Frederikshavn Municipality,Frederikshavn,Denmark,Europe,False,True,public,http://frederikshavn-kp13.cowi.webhouse.dk/dk/...,The assessment can be accessed (unrestricted) ...,Larger - covers the whole jurisdiction and adj...,2022.0,"Other, please specify: Assessment considers vu...",Dedicated team within jurisdiction,Adaptation plan,59234,2023.0,POINT (10.521 57.4427),02/07/2024 04:14:16 AM
702,Cities 2023,918147,Fanø Municipality,NaN,Denmark,Europe,False,False,public,Klimatilpasningsplan+2022-2029.pdf,The assessment has been attached,Same - covers entire jurisdiction and nothing ...,2022.0,A process has been established for prioritizin...,Consultant; Relevant department within jurisdi...,Adaptation goal(s) and adaptation plan,3427,2022.0,POINT (8.4145 55.413),02/07/2024 04:14:16 AM
732,Cities 2023,60433,Hvidovre Municipality,Hvidovre,Denmark,Europe,False,True,public,hvidovre_risikostyringsplan_vedtaget_28092021.pdf,The assessment has been attached and can be ac...,Partial - covers part of the jurisdiction and ...,2021.0,NaN,Relevant department within jurisdiction,Adaptation goal(s) and adaptation plan,53254,2022.0,POINT (12.4754 55.6425),02/07/2024 04:14:16 AM
813,Cities 2023,918147,Fanø Municipality,NaN,Denmark,Europe,False,False,public,Risk assessment related to heat.pdf,The assessment has been attached,Same - covers entire jurisdiction and nothing ...,2023.0,A process has been established to update the a...,Relevant department within jurisdiction,Adaptation goal(s) and adaptation plan,3427,2022.0,POINT (8.4145 55.413),02/07/2024 04:14:16 AM
865,Cities 2023,58671,Helsingør Municipality,Helsingør,Denmark,Europe,False,True,public,https://www.helsingor.dk/media/rydd13a4/klimat...,The assessment has been attached and can be ac...,Same - covers entire jurisdiction and nothing ...,2022.0,A process has been established for prioritizin...,Consultant; Dedicated team within jurisdiction,Adaptation goal(s) and adaptation plan,63399,2023.0,POINT (12.5921 56.0308),02/07/2024 04:14:16 AM
876,Cities 2023,58489,Høje-Taastrup Municipality,Hoeje-Taastrup,Denmark,Europe,False,True,public,Klimaplan_HJETAASTRUP_Engelsk 1.pdf,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2021.0,Assessment considers nature; Assessment consid...,"Consultant; Other, please specify: municipal c...",Adaptation goal(s),53053,2022.0,POINT (12.2898 55.6563),02/07/2024 04:14:16 AM
931,Cities 2023,58671,Helsingør Municipality,Helsingør,Denmark,Europe,False,True,public,https://helsingor.viewer.dkplan.niras.dk/plan/...,The assessment has been attached and can be ac...,Same - covers entire jurisdiction and nothing ...,2019.0,A process has been established for prioritizin...,Dedicated team within jurisdiction; Relevant d...,Adaptation goal(s) and adaptation plan,63399,2023.0,POINT (12.5921 56.0308),02/07/2024 04:14:16 AM
983,Cities 2023,31009,Copenhagen Municipality,Copenhagen,Denmark,Europe,True,True,public,https://international.kk.dk/sites/default/file...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2012.0,A process has been established for prioritizin...,Consultant; Dedicated team within jurisdiction...,Adaptation goal(s) and adaptation plan,644425,2022.0,POINT (12.5683 55.6761),02/07/2024 04:14:16 AM
985,Cities 2023,63543,Fredensborg Municipality,Fredensborg,Denmark,Europe,False,True,public,https://klimatilpasningsplan.fredensborg.dk,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2022.0,A process has been established to update the a...,Relevant department within jurisdiction,Adaptation goal(s) and adaptation plan,41721,2023.0,POINT (12.4058 55.9747),02/07/2024 04:14:16 AM
995,Cities 2023,60433,Hvidovre Municipality,Hvidovre,Denmark,Europe,False,True,public,https://www.hvidovre.dk/media/qadaro4w/strateg...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2020.0,Assessment includes sectors and/or urban syste...,Dedicated team within jurisdiction,Adaptation goal(s) and adaptation plan,53254,2022.0,POINT (12.4754 55.6425),02/07/2024 04:14:16 AM
1114,Cities 2023,60577,Frederikshavn Municipality,Frederikshavn,Denmark,Europe,False,True,public,http://energibyen.dk/sites/default/files/miljo...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2022.0,"Other, please specify: Assessment considers ri...",Dedicated team within jurisdiction,Adaptation plan,59234,2023.0,POINT (10.521 57.4427),02/07/2024 04:14:16 AM
1146,Cities 2023,58489,Høje-Taastrup Municipality,Hoeje-Taastrup,Denmark,Europe,False,True,public,Kommende lukning af Taastrup Valby Kildeplads.pdf,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2020.0,Assessment considers nature,"Consultant; Other, please specify: municipal e...",Adaptation goal(s),53053,2022.0,POINT (12.2898 55.6563),02/07/2024 04:14:16 AM
1156,Cities 2023,31009,Copenhagen Municipality,Copenhagen,Denmark,Europe,True,True,public,https://www.kk.dk/sites/default/files/agenda/1...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2021.0,A process has been established for prioritizin...,Dedicated team within jurisdiction; Relevant d...,Adaptation goal(s) and adaptation plan,644425,2022.0,POINT (12.5683 55.6761),02/07/2024 04:14:16 AM
1189,Cities 2023,60433,Hvidovre Municipality,Hvidovre,Denmark,Europe,False,True,public,https://www.hvidovre.dk/media/2kkdnh1t/strateg...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2014.0,Assessment includes sectors and/or urban syste...,Dedicated team within jurisdiction,Adaptation goal(s) and adaptation plan,53254,2022.0,POINT (12.4754 55.6425),02/07/2024 04:14:16 AM

In [465]:
cities_emissions_2016.columns

Index(['Organisation', 'Account No', 'Country', 'City Short Name', 'C40',
       'Reporting Year', 'Sector', 'Target boundary', 'Baseline year',
       'Baseline emissions (metric tonnes CO2e)',
       'Percentage reduction target', 'Target date', 'Comment',
       'City Location', 'Country Location'],
      dtype='object')

# COUNTRIES

In [466]:
countries = {}
country_id = 1


for index in cities_emissions_2016.index:
    _id = country_id
    name = cities_emissions_2016["Country"][index]
    location = cities_emissions_2016["Country Location"][index]
    
    countries[name]={"id":_id,"name":name,"location":location}
    country_id+=1

In [467]:
citywide_emissions_2016.columns

Index(['Account Number', 'City Name', 'Country', 'City Short Name', 'C40',
       'Reporting Year', 'Measurement Year', 'Boundary', 'Primary Methodology',
       'Methodology Details', 'Gases included',
       'Total City-wide Emissions (metric tonnes CO2e)',
       'Total Scope 1 Emissions (metric tonnes CO2e)',
       'Total Scope 2 Emissions (metric tonnes CO2e)',
       'Increase/Decrease from last year',
       'Reason for increase/decrease in emissions', 'Current Population Year',
       'Current Population', 'City GDP', 'GDP Currency', 'Year of GDP',
       'GDP Source', 'Average annual temperature (in Celsius)',
       ' Land area (in square km)', 'Average altitude (m)', 'City Location',
       'Country Location'],
      dtype='object')

In [468]:
len(countries)

36

In [469]:
for index in citywide_emissions_2016.index:
    _id = country_id
    name = citywide_emissions_2016["Country"][index]
    location = citywide_emissions_2016["Country Location"][index]
    if name not in countries:
        countries[name]={"id":_id,"name":name,"location":location}
        country_id+=1
    else:
        currentCountry = countries[name]
        if currentCountry["id"] == None or currentCountry["id"] == "":
            currentCountry["id"] = _id
        if currentCountry["name"] == None or currentCountry["name"] == "":
            currentCountry["name"] = name
        if currentCountry["location"] == None or currentCountry["location"] == "":
            currentCountry["location"] = location
        countries[name] = currentCountry

In [470]:
len(countries)

47

In [471]:
community_emissions_2017.columns

Index(['Account number', 'Organization', 'City', 'Country', 'Region', 'C40',
       'Access', 'Reporting year', 'Accounting year', 'Boundary', 'Protocol',
       'Protocol column', 'Gases included',
       'Total emissions (metric tonnes CO2e)', 'Scopes Included ',
       'Total Scope 1 Emissions (metric tonnes CO2e)',
       'Total Scope 2 Emissions (metric tonnes CO2e)', 'Comment',
       'Increase/Decrease from last year',
       'Reason for increase/decrease in emissions', 'Population',
       'Population year', 'GDP', 'GDP Currency', 'GDP Year', 'GDP Source',
       'Average annual temperature (in Celsius)', 'Average altitude (m)',
       'Land area (in square km)', 'City Location', 'Country Location'],
      dtype='object')

In [472]:
for index in community_emissions_2017.index:
    _id = country_id
    name = community_emissions_2017["Country"][index]
    location = community_emissions_2017["Country Location"][index]
    if name not in countries:
        countries[name]={"id":_id,"name":name,"location":location}
        country_id+=1
    else:
        currentCountry = countries[name]
        if currentCountry["id"] == None or currentCountry["id"] == "":
            currentCountry["id"] = _id
        if currentCountry["name"] == None or currentCountry["name"] == "":
            currentCountry["name"] = name
        if currentCountry["location"] == None or currentCountry["location"] == "":
            currentCountry["location"] = location
        countries[name] = currentCountry

In [473]:
len(countries)

55

In [474]:
cities_emissions_2017.columns

Index(['Account No', 'Organisation', 'City', 'Country', 'Region', 'Access',
       'C40', 'Reporting year', 'Type of target', 'Sector', 'Baseline year',
       'Baseline emissions (metric tonnes CO2e)',
       'Percentage reduction target', 'Target date',
       'Estimated business as usual absolute emissions in target year (metric tonnes CO2e)',
       '​Intensity unit (emissions per)', 'Comment', 'Population',
       'Population Year', 'City Location', 'Country Location'],
      dtype='object')

In [475]:
for index in cities_emissions_2017.index:
    _id = country_id
    name = cities_emissions_2017["Country"][index]
    location = cities_emissions_2017["Country Location"][index]
    if name not in countries:
        countries[name]={"id":_id,"name":name,"location":location}
        country_id+=1
    else:
        currentCountry = countries[name]
        if currentCountry["id"] == None or currentCountry["id"] == "":
            currentCountry["id"] = _id
        if currentCountry["name"] == None or currentCountry["name"] == "":
            currentCountry["name"] = name
        if currentCountry["location"] == None or currentCountry["location"] == "":
            currentCountry["location"] = location
        countries[name] = currentCountry

In [476]:
len(countries)

63

In [477]:
cities_risk_2023.columns

Index(['Questionnaire', 'Organization Number', 'Organization Name', 'City',
       'Country/Area', 'CDP Region', 'C40 City', 'GCoM City', 'Access',
       'Assessment attachment and/or direct link',
       'Confirm attachment/link provided',
       'Boundary of assessment relative to jurisdiction boundary',
       'Year of publication or approval', 'Factors considered in assessment',
       'Primary author(s) of assessment',
       'Does the city have adaptation goal(s) and/or an adaptation plan?',
       'Population', 'Population Year', 'City Location', 'Last update'],
      dtype='object')

In [478]:
#for index in cities_risk_2023.index:
#    _id = country_id
#    name = cities_risk_2023["Country/Area"][index]
#    if name not in countries:
#        countries[name]={"id":_id,"name":name,"location":location}
#        country_id+=1
#    else:
#        currentCountry = countries[name]
#        if currentCountry["id"] == None or currentCountry["id"] == "":
#            currentCountry["id"] = _id
#        if currentCountry["name"] == None or currentCountry["name"] == "" or str(currentCountry["name"]) == 'nan' :
#            currentCountry["name"] = name
#        countries[name] = currentCountry

In [479]:
data = []

for key in countries:
    data.append([countries[key]["id"],countries[key]["name"],countries[key]["location"]])
    
countries_df = pd.DataFrame(data, columns=['id','country_name','location'])

len(countries_df)

countries_df.to_csv("countries.csv", sep=',', encoding='utf-8',index=False)

## Cities

In [480]:
cities_emissions_2016.columns

Index(['Organisation', 'Account No', 'Country', 'City Short Name', 'C40',
       'Reporting Year', 'Sector', 'Target boundary', 'Baseline year',
       'Baseline emissions (metric tonnes CO2e)',
       'Percentage reduction target', 'Target date', 'Comment',
       'City Location', 'Country Location'],
      dtype='object')

In [481]:
cities = {}

for index in cities_emissions_2016.index:
    _id = cities_emissions_2016["Account No"][index]
    name = cities_emissions_2016["Organisation"][index]
    location = cities_emissions_2016["City Location"][index]
    avg_a_temp = None
    c40 = cities_emissions_2016["C40"][index] == "C40"
    land_area = None
    
    
    if _id not in cities:
        cities[_id]={"id":_id,"name":name,"country_id":None,"location":location,"avg_a_temp":avg_a_temp,"c40":c40,"land_area":land_area,"gcom":False}
    else:
        currentCity = cities[_id]
        if currentCity["name"] == None or currentCity["name"] == "":
            currentCountry["name"] = name
        if currentCity["location"] == None or currentCity["location"] == "":
            currentCity["location"] = location
        if currentCity["avg_a_temp"] == None or currentCity["avg_a_temp"] == "":
            currentCity["avg_a_temp"] = avg_a_temp
        if currentCity["c40"] == None or currentCity["c40"] == "":
            currentCity["c40"] = c40
        if currentCity["land_area"] == None or currentCity["land_area"] == "":
            currentCity["land_area"] = land_area
        currentCity[_id] = currentCity

In [482]:
len(cities)

176

In [483]:
citywide_emissions_2016.columns

Index(['Account Number', 'City Name', 'Country', 'City Short Name', 'C40',
       'Reporting Year', 'Measurement Year', 'Boundary', 'Primary Methodology',
       'Methodology Details', 'Gases included',
       'Total City-wide Emissions (metric tonnes CO2e)',
       'Total Scope 1 Emissions (metric tonnes CO2e)',
       'Total Scope 2 Emissions (metric tonnes CO2e)',
       'Increase/Decrease from last year',
       'Reason for increase/decrease in emissions', 'Current Population Year',
       'Current Population', 'City GDP', 'GDP Currency', 'Year of GDP',
       'GDP Source', 'Average annual temperature (in Celsius)',
       ' Land area (in square km)', 'Average altitude (m)', 'City Location',
       'Country Location'],
      dtype='object')

In [484]:
for index in citywide_emissions_2016.index:
    _id = citywide_emissions_2016["Account Number"][index]
    name = citywide_emissions_2016["City Name"][index]
    location = citywide_emissions_2016["City Location"][index]
    avg_a_temp = citywide_emissions_2016["Average annual temperature (in Celsius)"][index]
    c40 = citywide_emissions_2016["C40"][index] == "C40"
    land_area = citywide_emissions_2016[" Land area (in square km)"][index]
    
    
    if _id not in cities:
        cities[_id]={"id":_id,"name":name,"country_id":None,"location":location,"avg_a_temp":avg_a_temp,"c40":c40,"land_area":land_area,"gcom":False}
    else:
        currentCity = cities[_id]
        if currentCity["name"] == None or currentCity["name"] == "":
            currentCountry["name"] = name
        if currentCity["location"] == None or currentCity["location"] == "":
            currentCity["location"] = location
        if currentCity["avg_a_temp"] == None or currentCity["avg_a_temp"] == "":
            currentCity["avg_a_temp"] = avg_a_temp
        if currentCity["c40"] == None or currentCity["c40"] == "":
            currentCity["c40"] = c40
        if currentCity["land_area"] == None or currentCity["land_area"] == "":
            currentCity["land_area"] = land_area
        currentCity[_id] = currentCity

In [485]:
len(cities)

231

In [486]:
community_emissions_2017.columns

Index(['Account number', 'Organization', 'City', 'Country', 'Region', 'C40',
       'Access', 'Reporting year', 'Accounting year', 'Boundary', 'Protocol',
       'Protocol column', 'Gases included',
       'Total emissions (metric tonnes CO2e)', 'Scopes Included ',
       'Total Scope 1 Emissions (metric tonnes CO2e)',
       'Total Scope 2 Emissions (metric tonnes CO2e)', 'Comment',
       'Increase/Decrease from last year',
       'Reason for increase/decrease in emissions', 'Population',
       'Population year', 'GDP', 'GDP Currency', 'GDP Year', 'GDP Source',
       'Average annual temperature (in Celsius)', 'Average altitude (m)',
       'Land area (in square km)', 'City Location', 'Country Location'],
      dtype='object')

In [487]:
for index in community_emissions_2017.index:
    _id = community_emissions_2017["Account number"][index]
    name = community_emissions_2017["Organization"][index]
    location = community_emissions_2017["City Location"][index]
    avg_a_temp = community_emissions_2017["Average annual temperature (in Celsius)"][index]
    c40 = community_emissions_2017["C40"][index] == "C40"
    land_area = community_emissions_2017["Land area (in square km)"][index]
    
    
    if _id not in cities:
        cities[_id]={"id":_id,"name":name,"country_id":None,"location":location,"avg_a_temp":avg_a_temp,"c40":c40,"land_area":land_area,"gcom":False}
    else:
        currentCity = cities[_id]
        if currentCity["name"] == None or currentCity["name"] == "":
            currentCountry["name"] = name
        if currentCity["location"] == None or currentCity["location"] == "":
            currentCity["location"] = location
        if currentCity["avg_a_temp"] == None or currentCity["avg_a_temp"] == "":
            currentCity["avg_a_temp"] = avg_a_temp
        if currentCity["c40"] == None or currentCity["c40"] == "":
            currentCity["c40"] = c40
        if currentCity["land_area"] == None or currentCity["land_area"] == "":
            currentCity["land_area"] = land_area
        currentCity[_id] = currentCity

In [488]:
len(cities)

299

In [489]:
cities_emissions_2017.columns

Index(['Account No', 'Organisation', 'City', 'Country', 'Region', 'Access',
       'C40', 'Reporting year', 'Type of target', 'Sector', 'Baseline year',
       'Baseline emissions (metric tonnes CO2e)',
       'Percentage reduction target', 'Target date',
       'Estimated business as usual absolute emissions in target year (metric tonnes CO2e)',
       '​Intensity unit (emissions per)', 'Comment', 'Population',
       'Population Year', 'City Location', 'Country Location'],
      dtype='object')

In [490]:
for index in cities_emissions_2017.index:
    _id = cities_emissions_2017["Account No"][index]
    name = cities_emissions_2017["Organisation"][index]
    location = cities_emissions_2017["City Location"][index]
    avg_a_temp = None;
    c40 = cities_emissions_2017["C40"][index] == "C40"
    land_area = None
    
    if _id not in cities:
        cities[_id]={"id":_id,"name":name,"country_id":None,"location":location,"avg_a_temp":avg_a_temp,"c40":c40,"land_area":land_area,"gcom":False}
    else:
        currentCity = cities[_id]
        if currentCity["name"] == None or currentCity["name"] == "":
            currentCountry["name"] = name
        if currentCity["location"] == None or currentCity["location"] == "":
            currentCity["location"] = location
        if currentCity["avg_a_temp"] == None or currentCity["avg_a_temp"] == "":
            currentCity["avg_a_temp"] = avg_a_temp
        if currentCity["c40"] == None or currentCity["c40"] == "":
            currentCity["c40"] = c40
        if currentCity["land_area"] == None or currentCity["land_area"] == "":
            currentCity["land_area"] = land_area
        currentCity[_id] = currentCity

In [491]:
len(cities)

337

In [492]:
cities_risk_2023.columns

Index(['Questionnaire', 'Organization Number', 'Organization Name', 'City',
       'Country/Area', 'CDP Region', 'C40 City', 'GCoM City', 'Access',
       'Assessment attachment and/or direct link',
       'Confirm attachment/link provided',
       'Boundary of assessment relative to jurisdiction boundary',
       'Year of publication or approval', 'Factors considered in assessment',
       'Primary author(s) of assessment',
       'Does the city have adaptation goal(s) and/or an adaptation plan?',
       'Population', 'Population Year', 'City Location', 'Last update'],
      dtype='object')

In [493]:
for index in cities_risk_2023.index:
    isGcom = cities_risk_2023["GCoM City"][index]
    _id = cities_risk_2023["Organization Number"][index]
    
    if _id in cities:
        cities[_id]["gcom"] = isGcom

In [494]:
countries_df.columns

country_id = countries_df["id"][countries_df["country_name"] == "USA"]

In [495]:
for key in cities:
    
    country = None
    for index in cities_emissions_2016.index:
        if (cities_emissions_2016["Account No"][index] == key):
            country = cities_emissions_2016["Country"][index]
        
    if(country == None):
        for index in citywide_emissions_2016.index:
            if citywide_emissions_2016["Account Number"][index] == key:
                country = citywide_emissions_2016["Country"][index]
       
    if(country == None):
        for index in community_emissions_2017.index:
            if community_emissions_2017["Account number"][index] == key:
                country = community_emissions_2017["Country"][index]
       
    if(country == None):
        for index in cities_emissions_2017.index:
            if cities_emissions_2017["Account No"][index] == key:
                country = cities_emissions_2017["Country"][index]
    if str(country) != 'nan':
        country_id = int(countries_df["id"][countries_df["country_name"] == country].iloc[0])
        cities[key]["country_id"] = int(country_id)

In [496]:
cities[_id]={"id":_id,"name":name,"country_id":None,"location":location,"avg_a_temp":avg_a_temp,"c40":c40,"land_area":land_area,"gcom":False}

In [497]:
data = []

for key in cities:
    data.append([cities[key]["id"],cities[key]["name"],cities[key]["country_id"],cities[key]["location"],cities[key]["avg_a_temp"],cities[key]["c40"],cities[key]["land_area"],cities[key]["gcom"]])
cities_df = pd.DataFrame(data, columns=['id','city_name','country_id','city_location','average_annual_temperature','c40','land_area','gcom'])
cities_df["country_id"] = cities_df["country_id"].fillna(0).astype(int)
len(cities_df)

cities_df.to_csv("cities.csv", sep=',', encoding='utf-8',index=False)

# Sector

In [498]:
cities_emissions_2017.columns

Index(['Account No', 'Organisation', 'City', 'Country', 'Region', 'Access',
       'C40', 'Reporting year', 'Type of target', 'Sector', 'Baseline year',
       'Baseline emissions (metric tonnes CO2e)',
       'Percentage reduction target', 'Target date',
       'Estimated business as usual absolute emissions in target year (metric tonnes CO2e)',
       '​Intensity unit (emissions per)', 'Comment', 'Population',
       'Population Year', 'City Location', 'Country Location'],
      dtype='object')

In [499]:
sector ={}

sid = 1
for index in cities_emissions_2016.index:
    s = cities_emissions_2016["Sector"][index]
    if(str(s) == 'nan'):
        s = "Unspecified"
    elif ("Other:" in s):
        s = "Other"
    if s not in sector:
        sector[s]={"id":sid,"sector":s}
        sid +=1
        
for index in cities_emissions_2017.index:
    s = cities_emissions_2017["Sector"][index]
    if(str(s) == 'nan'):
        s = "Unspecified"
    elif ("Other:" in s):
        s = "Other"
    if s not in sector:
        sector[s]={"id":sid,"sector":s}
        sid +=1

sector

{'Total': {'id': 1, 'sector': 'Total'},
 'Unspecified': {'id': 2, 'sector': 'Unspecified'},
 'Waste': {'id': 3, 'sector': 'Waste'},
 'Other': {'id': 4, 'sector': 'Other'},
 'Buildings': {'id': 5, 'sector': 'Buildings'},
 'Transport': {'id': 6, 'sector': 'Transport'},
 'Transportation': {'id': 7, 'sector': 'Transportation'},
 'Stationary energy (buildings)': {'id': 8,
  'sector': 'Stationary energy (buildings)'},
 'Residential buildings': {'id': 9, 'sector': 'Residential buildings'},
 'Commercial buildings': {'id': 10, 'sector': 'Commercial buildings'},
 'Industrial buildings': {'id': 11, 'sector': 'Industrial buildings'},
 'Public buildings': {'id': 12, 'sector': 'Public buildings'},
 'Wastewater': {'id': 13, 'sector': 'Wastewater'}}

In [500]:
data = []

for key in sector:
    data.append([sector[key]["id"],sector[key]["sector"]])
    
sector_df = pd.DataFrame(data, columns=['id','sector_name'])

len(sector_df)

sector_df.to_csv("sectors.csv", sep=',', encoding='utf-8',index=False)

## Population

In [501]:
cities_emissions_2016.columns

Index(['Organisation', 'Account No', 'Country', 'City Short Name', 'C40',
       'Reporting Year', 'Sector', 'Target boundary', 'Baseline year',
       'Baseline emissions (metric tonnes CO2e)',
       'Percentage reduction target', 'Target date', 'Comment',
       'City Location', 'Country Location'],
      dtype='object')

In [502]:
citywide_emissions_2016.columns

Index(['Account Number', 'City Name', 'Country', 'City Short Name', 'C40',
       'Reporting Year', 'Measurement Year', 'Boundary', 'Primary Methodology',
       'Methodology Details', 'Gases included',
       'Total City-wide Emissions (metric tonnes CO2e)',
       'Total Scope 1 Emissions (metric tonnes CO2e)',
       'Total Scope 2 Emissions (metric tonnes CO2e)',
       'Increase/Decrease from last year',
       'Reason for increase/decrease in emissions', 'Current Population Year',
       'Current Population', 'City GDP', 'GDP Currency', 'Year of GDP',
       'GDP Source', 'Average annual temperature (in Celsius)',
       ' Land area (in square km)', 'Average altitude (m)', 'City Location',
       'Country Location'],
      dtype='object')

In [503]:
community_emissions_2017.columns

Index(['Account number', 'Organization', 'City', 'Country', 'Region', 'C40',
       'Access', 'Reporting year', 'Accounting year', 'Boundary', 'Protocol',
       'Protocol column', 'Gases included',
       'Total emissions (metric tonnes CO2e)', 'Scopes Included ',
       'Total Scope 1 Emissions (metric tonnes CO2e)',
       'Total Scope 2 Emissions (metric tonnes CO2e)', 'Comment',
       'Increase/Decrease from last year',
       'Reason for increase/decrease in emissions', 'Population',
       'Population year', 'GDP', 'GDP Currency', 'GDP Year', 'GDP Source',
       'Average annual temperature (in Celsius)', 'Average altitude (m)',
       'Land area (in square km)', 'City Location', 'Country Location'],
      dtype='object')

In [504]:
cities_emissions_2017.columns

Index(['Account No', 'Organisation', 'City', 'Country', 'Region', 'Access',
       'C40', 'Reporting year', 'Type of target', 'Sector', 'Baseline year',
       'Baseline emissions (metric tonnes CO2e)',
       'Percentage reduction target', 'Target date',
       'Estimated business as usual absolute emissions in target year (metric tonnes CO2e)',
       '​Intensity unit (emissions per)', 'Comment', 'Population',
       'Population Year', 'City Location', 'Country Location'],
      dtype='object')

In [505]:
population ={}

pid = 1

for index in citywide_emissions_2016.index:
    pop = citywide_emissions_2016["Current Population"][index]
    city_id = citywide_emissions_2016["Account Number"][index]
    pop_year = citywide_emissions_2016["Current Population Year"][index]
    if city_id+pop_year not in population:
        population[city_id + pop_year] = {"id":pid,"pop":pop,"pop_year":pop_year,"cid":city_id}
        pid+=1

for index in community_emissions_2017.index:
    pop = community_emissions_2017["Population"][index]
    city_id = community_emissions_2017["Account number"][index]
    pop_year = community_emissions_2017["Population year"][index]
    if city_id+pop_year not in population:
        population[city_id + pop_year] = {"id":pid,"pop":pop,"pop_year":pop_year,"cid":city_id}
        pid+=1
        
for index in cities_emissions_2017.index:
    pop = cities_emissions_2017["Population"][index]
    city_id = cities_emissions_2017["Account No"][index]
    pop_year = cities_emissions_2017["Population Year"][index]
    if city_id+pop_year not in population:
        population[city_id + pop_year] = {"id":pid,"pop":pop,"pop_year":pop_year,"cid":city_id}
        pid+=1

In [527]:
data = []

for key in population:
    data.append([population[key]["id"],population[key]["pop"],population[key]["pop_year"],population[key]["cid"]])
    
pop_df = pd.DataFrame(data, columns=['id','population_amount','population_year','city_id'])
pop_df['population_amount'] = pop_df['population_amount'].fillna(0).astype(int)
pop_df['city_id'] = pop_df['city_id'].fillna(0).astype(int)
pop_df['population_year'] = pop_df['population_year'].fillna(0).astype(int)
len(sector_df)

pop_df.to_csv("pop.csv", sep=',', encoding='utf-8',index=False)

## GDP

In [507]:
citywide_emissions_2016.columns

Index(['Account Number', 'City Name', 'Country', 'City Short Name', 'C40',
       'Reporting Year', 'Measurement Year', 'Boundary', 'Primary Methodology',
       'Methodology Details', 'Gases included',
       'Total City-wide Emissions (metric tonnes CO2e)',
       'Total Scope 1 Emissions (metric tonnes CO2e)',
       'Total Scope 2 Emissions (metric tonnes CO2e)',
       'Increase/Decrease from last year',
       'Reason for increase/decrease in emissions', 'Current Population Year',
       'Current Population', 'City GDP', 'GDP Currency', 'Year of GDP',
       'GDP Source', 'Average annual temperature (in Celsius)',
       ' Land area (in square km)', 'Average altitude (m)', 'City Location',
       'Country Location'],
      dtype='object')

In [508]:
community_emissions_2017.columns

Index(['Account number', 'Organization', 'City', 'Country', 'Region', 'C40',
       'Access', 'Reporting year', 'Accounting year', 'Boundary', 'Protocol',
       'Protocol column', 'Gases included',
       'Total emissions (metric tonnes CO2e)', 'Scopes Included ',
       'Total Scope 1 Emissions (metric tonnes CO2e)',
       'Total Scope 2 Emissions (metric tonnes CO2e)', 'Comment',
       'Increase/Decrease from last year',
       'Reason for increase/decrease in emissions', 'Population',
       'Population year', 'GDP', 'GDP Currency', 'GDP Year', 'GDP Source',
       'Average annual temperature (in Celsius)', 'Average altitude (m)',
       'Land area (in square km)', 'City Location', 'Country Location'],
      dtype='object')

In [509]:
citywide_emissions_2016.columns 

community_emissions_2017.columns




gdps ={}

gdpid = 1

for index in citywide_emissions_2016.index:
    gdp = citywide_emissions_2016["City GDP"][index]
    city_id = citywide_emissions_2016["Account Number"][index]
    curr = citywide_emissions_2016["GDP Currency"][index]
    year = citywide_emissions_2016["Year of GDP"][index]
    
    if(str(gdp) != 'nan' and str(year) != 'nan'):
        if city_id+year not in gdps:
            gdps[city_id+year] = {"id":gdpid,"gdp":gdp,"curr":curr,"cid":city_id,"year":year}
            gdpid+=1
    
    

for index in community_emissions_2017.index:
    gdp = community_emissions_2017["GDP"][index]
    city_id = community_emissions_2017["Account number"][index]
    curr = community_emissions_2017["GDP Currency"][index]
    year = community_emissions_2017["GDP Year"][index]

    if(str(gdp) != 'nan' and str(year) != 'nan'):
        if city_id+year not in gdps:
            gdps[city_id+year] = {"id":gdpid,"gdp":gdp,"curr":curr,"cid":city_id,"year":year}
            gdpid+=1

In [510]:
data = []

for key in gdps:
    data.append([gdps[key]["id"],gdps[key]["gdp"],gdps[key]["curr"],gdps[key]["cid"],gdps[key]["year"]])
    
gdp_df = pd.DataFrame(data, columns=['id','gdp','currency','city_id','gdp_year'])
gdp_df["gdp_year"] = gdp_df["gdp_year"].fillna(0).astype(int)
len(gdp_df)

gdp_df.to_csv("gdp.csv", sep=',', encoding='utf-8',index=False)

# Emission Target

In [511]:
cities_emissions_2017.columns

Index(['Account No', 'Organisation', 'City', 'Country', 'Region', 'Access',
       'C40', 'Reporting year', 'Type of target', 'Sector', 'Baseline year',
       'Baseline emissions (metric tonnes CO2e)',
       'Percentage reduction target', 'Target date',
       'Estimated business as usual absolute emissions in target year (metric tonnes CO2e)',
       '​Intensity unit (emissions per)', 'Comment', 'Population',
       'Population Year', 'City Location', 'Country Location'],
      dtype='object')

In [512]:

cities_emissions_2016.columns

Index(['Organisation', 'Account No', 'Country', 'City Short Name', 'C40',
       'Reporting Year', 'Sector', 'Target boundary', 'Baseline year',
       'Baseline emissions (metric tonnes CO2e)',
       'Percentage reduction target', 'Target date', 'Comment',
       'City Location', 'Country Location'],
      dtype='object')

In [513]:
targets = {}
tid = 1

for index in cities_emissions_2016.index:
    _id = tid
    baseline_year = cities_emissions_2016["Baseline year"][index]
    target_year = cities_emissions_2016["Target date"][index]
    baseline_emissions = cities_emissions_2016["Baseline emissions (metric tonnes CO2e)"][index]
    percentage_reduction_target = cities_emissions_2016["Percentage reduction target"][index]
    city_id = cities_emissions_2016["Account No"][index]
    sector = cities_emissions_2016["Sector"][index]
    sector_id = None

    pkey = str(sector)+str(city_id)+str(target_year);
    
    if pkey not in targets:
        targets[pkey]={"id":_id,"baseline_year":baseline_year,"target_year":target_year,"baseline_emissions":baseline_emissions,"percentage_reduction_target":percentage_reduction_target,"city_id":city_id,"sector_id":sector_id,"sector":sector}
        tid +=1
    else:
        currentTarget = targets[pkey]
        if currentTarget["baseline_year"] == None or currentTarget["baseline_year"] == "" or str(currentTarget["baseline_year"]) == 'nan':
            currentTarget["baseline_year"] = baseline_year
        if currentTarget["target_year"] == None or currentTarget["target_year"] == "" or str(currentTarget["target_year"]) == 'nan':
            currentTarget["target_year"] = target_year
        if currentTarget["baseline_emissions"] == None or currentTarget["baseline_emissions"] == "" or str(currentTarget["baseline_emissions"]) == 'nan':
            currentTarget["baseline_emissions"] = baseline_emissions
        if currentTarget["percentage_reduction_target"] == None or currentTarget["percentage_reduction_target"] == "" or str(currentTarget["percentage_reduction_target"]) == 'nan':
            currentTarget["percentage_reduction_target"] = percentage_reduction_target
        if currentTarget["city_id"] == None or currentTarget["city_id"] == "" or str(currentTarget["city_id"]) == 'nan':
            currentTarget["city_id"] = city_id
        if currentTarget["sector"] == None or currentTarget["sector"] == "" or str(currentTarget["sector"]) == 'nan':
            currentTarget["sector"] = sector

In [514]:
len(targets)

268

In [515]:
for index in cities_emissions_2017.index:
    _id = tid
    baseline_year = cities_emissions_2017["Baseline year"][index]
    target_year = cities_emissions_2017["Target date"][index]
    baseline_emissions = cities_emissions_2017["Baseline emissions (metric tonnes CO2e)"][index]
    percentage_reduction_target = cities_emissions_2017["Percentage reduction target"][index]
    city_id = cities_emissions_2017["Account No"][index]
    sector = cities_emissions_2017["Sector"][index]
    sector_id = None

    pkey = str(sector)+str(city_id)+str(target_year);
    
    if pkey not in targets:
        targets[pkey]={"id":_id,"baseline_year":baseline_year,"target_year":target_year,"baseline_emissions":baseline_emissions,"percentage_reduction_target":percentage_reduction_target,"city_id":city_id,"sector_id":sector_id,"sector":sector}
        tid +=1
    else:
        currentTarget = targets[pkey]
        if currentTarget["baseline_year"] == None or currentTarget["baseline_year"] == "" or str(currentTarget["baseline_year"]) == 'nan':
            currentTarget["baseline_year"] = baseline_year
        if currentTarget["target_year"] == None or currentTarget["target_year"] == "" or str(currentTarget["target_year"]) == 'nan':
            currentTarget["target_year"] = target_year
        if currentTarget["baseline_emissions"] == None or currentTarget["baseline_emissions"] == "" or str(currentTarget["baseline_emissions"]) == 'nan':
            currentTarget["baseline_emissions"] = baseline_emissions
        if currentTarget["percentage_reduction_target"] == None or currentTarget["percentage_reduction_target"] == "" or str(currentTarget["percentage_reduction_target"]) == 'nan':
            currentTarget["percentage_reduction_target"] = percentage_reduction_target
        if currentTarget["city_id"] == None or currentTarget["city_id"] == "" or str(currentTarget["city_id"]) == 'nan':
            currentTarget["city_id"] = city_id
        if currentTarget["sector"] == None or currentTarget["sector"] == "" or str(currentTarget["sector"]) == 'nan':
            currentTarget["sector"] = sector

In [516]:
len(targets)

657

In [517]:
for key in targets:
    s = None;
    if "Other:" in str(targets[key]["sector"]):
        targets[key]["sector_id"] = sector_df["id"][sector_df["sector_name"] == "Other"].iloc[0]
    elif str(targets[key]["sector"]) == 'nan':
        targets[key]["sector_id"] = sector_df["id"][sector_df["sector_name"] == "Unspecified"].iloc[0]
    else:
        targets[key]["sector_id"] = sector_df["id"][sector_df["sector_name"] == targets[key]["sector"]].iloc[0]

In [518]:
for key in targets:
    if "Other:" in str(targets[key]["target_year"]):
        targets[key]["target_year"] = targets[key]["target_year"].split("Other:")[1]
    if "Other" in str(targets[key]["baseline_year"]):
        targets[key]["baseline_year"] = None

In [531]:
data = []

for key in targets:
    data.append([targets[key]["id"],targets[key]["baseline_year"],targets[key]["target_year"],targets[key]["baseline_emissions"],targets[key]["percentage_reduction_target"],targets[key]["city_id"],targets[key]["sector_id"]])
    
target_df = pd.DataFrame(data, columns=['id','Baseline_year','target_year','baseline_emissions','percentage_reduction_target','city_id','sector_id'])
for index in target_df.index:
    if(target_df["target_year"][index] == None or target_df["target_year"][index] == '' or str(target_df["target_year"][index]) == 'nan' ):
        target_df["target_year"][index] = int(0)
    else:
        target_df["target_year"][index] = int(target_df["target_year"][index])
len(target_df)

target_df.to_csv("target.csv", sep=',', encoding='utf-8',index=False)

/var/folders/jj/6mz63v6n0b5f1hlgmlnwgd7r0000gn/T/ipykernel_91146/3466974950.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  target_df["target_year"][index] = int(0)
/var/folders/jj/6mz63v6n0b5f1hlgmlnwgd7r0000gn/T/ipykernel_91146/3466974950.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  target_df["target_year"][index] = int(target_df["target_year"][index])

# Emissions data

In [520]:
citywide_emissions_2016.columns

Index(['Account Number', 'City Name', 'Country', 'City Short Name', 'C40',
       'Reporting Year', 'Measurement Year', 'Boundary', 'Primary Methodology',
       'Methodology Details', 'Gases included',
       'Total City-wide Emissions (metric tonnes CO2e)',
       'Total Scope 1 Emissions (metric tonnes CO2e)',
       'Total Scope 2 Emissions (metric tonnes CO2e)',
       'Increase/Decrease from last year',
       'Reason for increase/decrease in emissions', 'Current Population Year',
       'Current Population', 'City GDP', 'GDP Currency', 'Year of GDP',
       'GDP Source', 'Average annual temperature (in Celsius)',
       ' Land area (in square km)', 'Average altitude (m)', 'City Location',
       'Country Location'],
      dtype='object')

In [521]:
community_emissions_2017.columns

Index(['Account number', 'Organization', 'City', 'Country', 'Region', 'C40',
       'Access', 'Reporting year', 'Accounting year', 'Boundary', 'Protocol',
       'Protocol column', 'Gases included',
       'Total emissions (metric tonnes CO2e)', 'Scopes Included ',
       'Total Scope 1 Emissions (metric tonnes CO2e)',
       'Total Scope 2 Emissions (metric tonnes CO2e)', 'Comment',
       'Increase/Decrease from last year',
       'Reason for increase/decrease in emissions', 'Population',
       'Population year', 'GDP', 'GDP Currency', 'GDP Year', 'GDP Source',
       'Average annual temperature (in Celsius)', 'Average altitude (m)',
       'Land area (in square km)', 'City Location', 'Country Location'],
      dtype='object')

In [522]:
inc_dec_dict = {"This is our first year of calculation" : 1, "Increased": 2, "Decreased": 3,"Stayed the same": 4, "Other" : 5, 'nan':6}

In [523]:
emissions = {}
eid = 1

for index in citywide_emissions_2016.index:
    _id = eid
    reporting_year = citywide_emissions_2016["Reporting Year"][index]
    messurement_year = citywide_emissions_2016["Measurement Year"][index].split("/")[-1].split(" ")[0]
    total_emissions = citywide_emissions_2016["Total City-wide Emissions (metric tonnes CO2e)"][index]
    total_scope_1_emissions = citywide_emissions_2016["Total Scope 1 Emissions (metric tonnes CO2e)"][index]
    total_scope_2_emissions = citywide_emissions_2016["Total Scope 2 Emissions (metric tonnes CO2e)"][index]
    increase_Decrease_from_last_year = inc_dec_dict[str(citywide_emissions_2016["Increase/Decrease from last year"][index])]
    city_id = citywide_emissions_2016["Account Number"][index]

    pkey = str(city_id)+str(reporting_year);
    
    if pkey not in emissions:
        emissions[pkey]={"id":_id,"reporting_year":reporting_year,"messurement_year":messurement_year,"total_emissions":total_emissions,"total_scope_1_emissions":total_scope_1_emissions,"total_scope_2_emissions":total_scope_2_emissions,"increase_Decrease_from_last_year":increase_Decrease_from_last_year,"city_id":city_id}
        eid +=1
    else:
        currentTarget = emissions[pkey]
        if currentTarget["reporting_year"] == None or currentTarget["reporting_year"] == "" or str(currentTarget["reporting_year"]) == 'nan':
            currentTarget["reporting_year"] = reporting_year
        if currentTarget["messurement_year"] == None or currentTarget["messurement_year"] == "" or str(currentTarget["messurement_year"]) == 'nan':
            currentTarget["messurement_year"] = target_year
        if currentTarget["total_emissions"] == None or currentTarget["total_emissions"] == "" or str(currentTarget["total_emissions"]) == 'nan':
            currentTarget["total_emissions"] = baseline_emissions
        if currentTarget["total_scope_1_emissions"] == None or currentTarget["total_scope_1_emissions"] == "" or str(currentTarget["total_scope_1_emissions"]) == 'nan':
            currentTarget["total_scope_1_emissions"] = percentage_reduction_target
        if currentTarget["total_scope_2_emissions"] == None or currentTarget["total_scope_2_emissions"] == "" or str(currentTarget["total_scope_2_emissions"]) == 'nan':
            currentTarget["total_scope_2_emissions"] = total_scope_2_emissions
        if currentTarget["increase_Decrease_from_last_year"] == None or currentTarget["increase_Decrease_from_last_year"] == "" or str(currentTarget["increase_Decrease_from_last_year"]) == 'nan':
            currentTarget["increase_Decrease_from_last_year"] = increase_Decrease_from_last_year
        if currentTarget["city_id"] == None or currentTarget["city_id"] == "" or str(currentTarget["city_id"]) == 'nan':
            currentTarget["city_id"] = increase_Decrease_from_last_year

In [524]:
for index in community_emissions_2017.index:
    _id = eid
    reporting_year = community_emissions_2017["Reporting year"][index]
    messurement_year = community_emissions_2017["Accounting year"][index].split(" - ")[-1].split("-")[0]
    total_emissions = community_emissions_2017["Total emissions (metric tonnes CO2e)"][index]
    total_scope_1_emissions = community_emissions_2017["Total Scope 1 Emissions (metric tonnes CO2e)"][index]
    total_scope_2_emissions = community_emissions_2017["Total Scope 2 Emissions (metric tonnes CO2e)"][index]
    if("Other:" in str(community_emissions_2017["Increase/Decrease from last year"][index])):
        increase_Decrease_from_last_year = inc_dec_dict["Other"]
    else:
        increase_Decrease_from_last_year = inc_dec_dict[str(community_emissions_2017["Increase/Decrease from last year"][index])]
        
    city_id = community_emissions_2017["Account number"][index]

    pkey = str(city_id)+str(reporting_year);
    
    if pkey not in emissions:
        emissions[pkey]={"id":_id,"reporting_year":reporting_year,"messurement_year":messurement_year,"total_emissions":total_emissions,"total_scope_1_emissions":total_scope_1_emissions,"total_scope_2_emissions":total_scope_2_emissions,"increase_Decrease_from_last_year":increase_Decrease_from_last_year,"city_id":city_id}
        eid +=1
    else:
        currentTarget = emissions[pkey]
        if currentTarget["reporting_year"] == None or currentTarget["reporting_year"] == "" or str(currentTarget["reporting_year"]) == 'nan':
            currentTarget["reporting_year"] = reporting_year
        if currentTarget["messurement_year"] == None or currentTarget["messurement_year"] == "" or str(currentTarget["messurement_year"]) == 'nan':
            currentTarget["messurement_year"] = target_year
        if currentTarget["total_emissions"] == None or currentTarget["total_emissions"] == "" or str(currentTarget["total_emissions"]) == 'nan':
            currentTarget["total_emissions"] = baseline_emissions
        if currentTarget["total_scope_1_emissions"] == None or currentTarget["total_scope_1_emissions"] == "" or str(currentTarget["total_scope_1_emissions"]) == 'nan':
            currentTarget["total_scope_1_emissions"] = percentage_reduction_target
        if currentTarget["total_scope_2_emissions"] == None or currentTarget["total_scope_2_emissions"] == "" or str(currentTarget["total_scope_2_emissions"]) == 'nan':
            currentTarget["total_scope_2_emissions"] = total_scope_2_emissions
        if currentTarget["increase_Decrease_from_last_year"] == None or currentTarget["increase_Decrease_from_last_year"] == "" or str(currentTarget["increase_Decrease_from_last_year"]) == 'nan':
            currentTarget["increase_Decrease_from_last_year"] = increase_Decrease_from_last_year
        if currentTarget["city_id"] == None or currentTarget["city_id"] == "" or str(currentTarget["city_id"]) == 'nan':
            currentTarget["city_id"] = increase_Decrease_from_last_year

In [525]:
data = []

for key in emissions:
    data.append([emissions[key]["id"],emissions[key]["reporting_year"],emissions[key]["messurement_year"],emissions[key]["total_emissions"],emissions[key]["total_scope_1_emissions"],emissions[key]["total_scope_2_emissions"],emissions[key]["increase_Decrease_from_last_year"],emissions[key]["city_id"]])
    
emission_df = pd.DataFrame(data, columns=['id','reporting_year','target_year','measurement_year','total_emissions','total_scope_1_emissions','total_scope_2_emissions','emission_status_id','city_id'])

len(emission_df)

emission_df.to_csv("emission.csv", sep=',', encoding='utf-8',index=False)

ValueError: 9 columns passed, passed data had 8 columns

In [ ]:


inc= {"id": [1,2,3,4,5,6] , "status_name":["This is our first year of calculation","Increased","Decreased","Stayed the same","Other","N/A"]}

lars = pd.DataFrame.from_dict(inc)

lars.to_csv("emission_status.csv", sep=',', encoding='utf-8',index=False)